patterns:
  product-details:
    fields:
    - name: product-title
      type: string
      example: "Snowball"
    - name: product-details
      type: string
      example: "Vanilla and Citrus"
    - name: term
      type: value
      example: "$8.99"
