patterns:
  homepage-banner:
    title: "Main Banner"
    description: This is the main banner. It should be used only on homepage
    fields:
      - name: title
        type: string
        example: "A GIFT FROM NATURE"
      - name: details
        type: string
        example: "Homemade soap made with all natural ingredients"
      - name: image
        type: image
        example: "banner.jpg"
  homepage-mini-banner:
    title: "Mini Banner"
    description: This is a mini banner. This is only on the main page.
